[package]
name = "win-butler"
version = "0.1.0"
description = "App desktop de limpeza e manutenção do Windows 11"
authors = ["you"]
edition = "2021"
rust-version = "1.77"

[lib]
name = "win_butler_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.32"
chrono = { version = "0.4", features = ["clock"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
